### PR TITLE
Escaping for PowerShell after whitespace with `{interpolation:true}`

### LINKED ISSUE #320: Missing escaping for PowerShell for certain characters after whitespace with `interpolation:true`
# Bug Report

- **Shescape version**: [v1.5.6](https://github.com/ericcornelissen/shescape/releases/tag/v1.5.6)
- **Operating system**: Windows
- **Shell**: PowerShell

## Description

When using `shescape.escape(arg, { interpolation: true })`/`shescape.escapeAll(args, { interpolation: true })` (like [the recipe](https://github.com/ericcornelissen/shescape/blob/5ed7527b153d830cb29de80ff1755e15809fb58e/docs/recipes.md#with-shescapeescape)) some characters are not properly escaped if they appear after a whitespace character.

Relates to #323

### Actual Behaviour

- `echo a @b` -> `a`
- `echo a ]b` -> `a ] b`
- `echo a <b` -> **error**
- `echo a 1>b` -> **nothing**
- `echo a 2>b` -> **nothing**
- `echo a 3>b` -> **nothing**
- `echo a 4>b` -> **nothing**
- `echo a 5>b` -> **nothing**
- `echo a 6>b` -> **nothing**
- `echo a *>b` -> **nothing**

### Expected Behaviour

- `echo a @b` -> `a @b`
- `echo a ]b` -> `a ]b`
- `echo a <b` -> `a <b`
- `echo a 1>b` -> `a 1>b`
- `echo a 2>b` -> `a 2>b`
- `echo a 3>b` -> `a 3>b`
- `echo a 4>b` -> `a 4>b`
- `echo a 5>b` -> `a 5>b`
- `echo a 6>b` -> `a 6>b`
- `echo a *>b` -> `a *>b`

## Working Example

This was found as part of #318, relevant crash files:

- [crash-74cd192a0b85f46497a85e0b229630c55c306ce8904ca3d7e362c0ad81fa1088.zip](https://github.com/ericcornelissen/shescape/files/9049551/crash-74cd192a0b85f46497a85e0b229630c55c306ce8904ca3d7e362c0ad81fa1088.zip)

### PR DESCRIPTION
**Pull request by ericcornelissen**
Closes #320 

Fuzzing for this depends on #318

### CODE REVIEW

File: test/fixtures/win.cjs [hunk 1]
```diff
@@ -457,6 +457,10 @@ module.exports.escape = {
         input: "a@b@c",
         expected: { interpolation: "a@b@c", noInterpolation: "a@b@c" },
       },
+      {
+        input: "a @b",
+        expected: { interpolation: "a `@b", noInterpolation: "a @b" },
+      },
```
Comment (ericcornelissen) [inline test/fixtures/win.cjs:463]: Is escaping (of this and all other characters covered by this Pull Request) also necessary after other whitespace characters? Whether "yes" or "no", there should be test cases for those other whitespace characters as well.
